### ISSUE TITLE
Add more API operations for syncs (2)

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/rails_app#16]
**Is your feature request related to a problem? Please describe.**
When a sync gets stuck, blocked, or incorrectly queued, you cannot resolve it from the API.

**Describe the solution you'd like**
Add a way to cancel, update, and re-enqueue a sync.

**Describe alternatives you've considered**
- skipping
- deleting

**Comment by mattgmarcus** [comment]
Looks good to me. We can probably hold off on `update` unless you want to add it. Skipping and cancelling are probably the two we'd want
