### ISSUE TITLE
Disassociate user from ledger authentication

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/rails_app#21]
**Is your feature request related to a problem? Please describe.**
When you want to authenticate a new ledger, you must create a user as `current_user` is used to determine the `organization`.  When using the app solely for authentication, it may not make sense to create users.  You may only need organizations and ledger authentication.

**Describe the solution you'd like**
- Make it possible to authenticate a ledger without `current_user`
- Potentially add `organization` to `AuthToken` to signal that there will be no user session.  Or maybe create a new `LedgerAuthToken` table.

**Comment by mattgmarcus** [comment]
This looks good. If it's helpful color, here's what a user in MT will do and how it interacts with this
```
In MT, someone clicks "sync with quickbooks"
MT server issues "Create Organization" API call to Ledger Sync App
MT server generates hits "Create Auth Token" API in Ledger Sync App
Using the returned auth token, MT client redirects user to ledger sync which redirects to QBO, and back to MT after auth
```

**Comment by ryanwjackson** [comment]
@mattgmarcus 

I'm working on this, and I am using the `AuthToken` with a polymorphic `resource` association.  It can be a User or an Organization.  How we are authenticating using Warden, `current_user` will return either object depending on the token.

I assume there are certain actions we do not want individuals to be able to take if they are not logged in as a User, right?  I need to work on scoping that but wanted to check before I made the decision on that divide.  Right now it really only seems like ledger management, but maybe it's just ledger connection?

I'm not totally sold on the solution as it feels a bit hacky, so maybe we can chat on it.

**Comment by mattgmarcus** [comment]
This is definitely a bit hacky. I'm also unsure how I feel about it.

If we think about it, the only problem I'm trying to solve is the auth redirect flow. Perhaps we can just keep the AuthToken table as it was and create a separate concept to allow the auth redirect. We could make another table like OrganizationAuthToken. I suppose we could keep the AuthToken polymorphic as you have it in the PR, but that seems unnecessary if we're just unblocking one use case.

Another option is you could not even have a table for that organization auth. Instead, we could just auth the redirect call using the ledger app's secret key and store the current organization in a cache. 

We can talk this one over. Like you though, I'm not sold on this approach. I left some comments on the PR anyway

**Comment by ryanwjackson** [comment]
After discussion, we will not be implementing this.  Instead a user will be required for authentication.  The "downside" is that an `email` is a required for a `User`.  To circumvent that for providers that only use this app for ledger authentication, we will add a config to disable user email notifications (#31).  

We decided to keep the User requirement, because it provides the ability to log and audit actions based on users.
