### ISSUE TITLE
Add API index pagination

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/rails_app#25]
**Is your feature request related to a problem? Please describe.**
There are no index API routes, because we do not yet support pagination.

**Describe the solution you'd like**
- Add `GET /syncs`
- Add `GET /resources`
- Add `GET /ledger_resources`
- Add `GET /organizations`
- Add `GET /users`
- Add pagination (ref: https://github.com/LedgerSync/temp_app/issues/9#issuecomment-527474444):

> You can use https://github.com/davidcelis/api-pagination and https://github.com/kaminari/kaminari
> 
> with this in `config/initializers/api_pagination.rb`
> ```ruby
> # frozen_string_literal: true
> 
> Kaminari.configure do |config|
>   config.default_per_page = 25
>   config.max_per_page     = 100
> end
> 
> ApiPagination.configure do |config|
>   config.paginator = :kaminari
> 
>   config.page_header = "X-Page"
>   config.total_header = "X-Total-Count"
>   config.per_page_header = "X-Per-Page"
> 
>   config.page_param = :page
>   config.per_page_param = :per_page
> end
> ```

**Comment by ryanwjackson** [comment]
@mattgmarcus It seems that `ApiPagination` only returns a JSON array for the API response.  I had originally thought that we would get a hash list object like the following:

```ruby
{
  object: 'list',
  data: [
   ...
  ]
}
```

Do you guys just return a list?  Do you wrap it in something like a list object?  If so, how?  Also, it does support [JSON API](http://jsonapi-rb.org), so we could just switch to standardize the whole API using that.

Thoughts?

**Comment by mattgmarcus** [comment]
We just return a list (here's an example https://docs.moderntreasury.com/docs/internal-account-response).

I don't think it's that much easier to encapsulate it in an object. That being said, I'm fine doing it however you feel comfortable. As a consumer of the API, either is easy enough. 
If using the JSON API is going to be a big rewrite, I'd prefer not to throw that wrench in there though
