### ISSUE TITLE
API endpoint to search ledger entities

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/rails_app#26]
**Is your feature request related to a problem? Please describe.**
As a user of ledger sync, I would like to have an API endpoint I can hit to search entities in my ledger. For example, if I'm connected to QBO, I may want to search my customers and vendors, expenses, invoices, etc.

**Describe the solution you'd like**
We probably only need 1 endpoint, sort of modeled like we do for `/sync`. You can pass it the resource type you want to search. Searching shouldn't create any database records in ledger sync. You'd probably also want to require a ledger ID as a param too, so you know which ledger to search within

**Describe alternatives you've considered**
We could have an endpoint per resource, but that sounds pretty intensive.

**Additional context**

**Comment by ryanwjackson** [comment]
Just putting some thoughts here, but let's discuss. 

I like the idea of doing better scoped routes, as we can easily make that dynamic and grow as `ledger_sync` adds more resources.  So I was thinking something like the following:

```
GET /search/ledger/:ledger_id/customers
GET /search/ledger/:ledger_id/payments
GET /search/ledger/:ledger_id/vendors
etc.
```

Some questions I have though:

1. Isn't it likely you will want to scope this to an Organization as well?  If so, it may be odd to do something like `GET /search/ledger/:ledger_id/customers?organization=org_123` if the ledger also implements an `organization` for their notion of a customer.

2. In the lib, we have the concept of "Searchers."  Our idea is that you could optimize for different types of queries, for example "QuickBooksOnline::Customer::NameSearcher" to check by only name, where "QuickBooksOnline::Customer::Searcher" would accept more parameters.  Perhaps that's an over-optimization though.  We aren't currently leveraging it anyway.

3. There is no way to know which attributes you can search on from the lib currently.  For example, [QBO customer search is done like this](https://github.com/LedgerSync/ledger_sync/blob/7fed7a5205dafc8d2e186e581488cc63d7678f00/lib/ledger_sync/adaptors/quickbooks_online/customer/searcher.rb#L19).  QBO API uses a query interface for searching.  We can abstract out the notion of a searchable param.  It may just vary by adaptor how those then get represented when hitting their API.

4. I probably just don't know the standards, but search params are passed through GET.  And unless we also implement something like a query interface for that, then it will inevitably get crazy with things like `amount >= x`.  Any recommendations on the best way to build a search API?

**Comment by ryanwjackson** [comment]
Discussed on call:

1. The ledger is mapped to an organization, so no need to pass it.
2. Restrict lib to have one searcher per resource per adaptor.
3. We can focus on this next, as MVP is essentially just an index
4. Just ignore ranges and such for now.

@mattgmarcus I'm struggling with what data to return here:

- One option is to return only what the lib returns in a JSON document.  So this would not query the app DB for any connection to existing data.  There probably are some advantages here for speed, so maybe this should be an option.

- But at some point you're likely going to want to know if this is already in the app DB associated with an `external_id` in your system.

- Here is the data we have to work with:

a. Ledger API response
b. LedgerSync lib resource (what the API response gets translated into)
c. The associated `LedgerResource`s (there can be multiple as we are just matching on `resource_ledger_id` and `ledger_id`) in the app if it exists.  And if so, that makes to a `Ledger` and a `Resource`.  The only  data (right now) in the app that isn't in the ledger's API search result is the `external_id` which is stored on the `Resource`.

So here is an attempt to pull all this together:

```ruby
{
  object: 'list',
  data: [
    {
      object: 'search/ledger_resource',
      object: 'ledger_resource',
      id: nil, # Can be nil if not in app DB
      ledger: 'ldgr_1234', # Present from request URL
      resource: { 
        object: 'resource',
        type: 'customer',
        id: nil, # Can be nil if not in app DB
        external_id: nil, # Can be nil if not in app DB
        resource_ledger_id: '1234',
        data: {
          name: 'foo',
          phone_number: 'bar',
          ...
        }
      }
    },
    ...
  ]

}
```

**Comment by ryanwjackson** [comment]
From call:

- A result from the ledger with a `resource_ledger_id` can have multiple app resources attached to it.
- Just start with ledger results, not attached to any app data.
- Maybe rename to `search/result`, `search/ledger_result`, `search/raw_result`, etc.
- Include raw API response data from ledger
