### ISSUE TITLE
Expire auth tokens when they're used

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/rails_app#35]
It appears that auth tokens aren't being expired anywhere. Where should that happen?

**Comment by ryanwjackson** [comment]
https://github.com/LedgerSync/rails_app/blob/master/app/lib/forms/auth_tokens/use.rb#L33 checks https://github.com/LedgerSync/rails_app/blob/master/app/models/auth_token.rb#L32 (which provides the time limit).

And all old ones are expired when a new one is created: https://github.com/LedgerSync/rails_app/blob/master/app/lib/forms/auth_tokens/create.rb#L32

Let me know if we want different behavior.

**Comment by mattgmarcus** [comment]
Ah okay, I see. I just misunderstood the behavior. This is fine
