### ISSUE TITLE
Idempotency Key bug

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/rails_app#36]
Should this be `idempotency_key.request_body != request_body`
https://github.com/LedgerSync/rails_app/blob/master/app/controllers/concerns/api/idempotentable.rb#L56

The reason is that the error message is `The idempotency key (#{idempotency_key}) has already been used with a different request body`

**Comment by ryanwjackson** [comment]
Yes, and we should write a test for this too.  Feel free to assign to me and I can take care of next week.
